// Package cmd provides the Cobra root command that launches the Snappy TUI.
package cmd

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	tea "charm.land/bubbletea/v2"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	"github.com/cboone/snappy/internal/config"
	"github.com/cboone/snappy/internal/logger"
	"github.com/cboone/snappy/internal/platform"
	"github.com/cboone/snappy/internal/service"
	"github.com/cboone/snappy/internal/tui"
)

var (
	cfgFile string
	version string
	rootCmd = &cobra.Command{
		Use:           "snappy",
		Short:         "Automatically increase your Time Machine snapshot frequency",
		SilenceUsage:  true,
		SilenceErrors: true,
		RunE:          runTUI,
	}
)

// usageTemplate is based on Cobra's default usage template (v1.10.2) with two
// changes to the Usage section:
//  1. Commands that are both runnable and have subcommands print a single
//     combined line instead of separate lines for [flags] and [command].
//  2. useArgs extracts positional-arg placeholders from the Use field so that
//     Cobra's autogenerated commands (e.g. help [command]) display them.
const usageTemplate = `Usage:{{if or .Runnable .HasAvailableSubCommands}}
  {{.CommandPath}}{{with useArgs .}} {{.}}{{end}}{{if .HasAvailableSubCommands}} [command]{{end}}{{if .HasAvailableFlags}} [flags]{{end}}{{end}}{{if gt (len .Aliases) 0}}

Aliases:
  {{.NameAndAliases}}{{end}}{{if .HasExample}}

Examples:
{{.Example}}{{end}}{{if .HasAvailableSubCommands}}{{$cmds := .Commands}}{{if eq (len .Groups) 0}}

Available Commands:{{range $cmds}}{{if (or .IsAvailableCommand (eq .Name "help"))}}
  {{rpad .Name .NamePadding }} {{.Short}}{{end}}{{end}}{{else}}{{range $group := .Groups}}

{{.Title}}{{range $cmds}}{{if (and (eq .GroupID $group.ID) (or .IsAvailableCommand (eq .Name "help")))}}
  {{rpad .Name .NamePadding }} {{.Short}}{{end}}{{end}}{{end}}{{if not .AllChildCommandsHaveGroup}}

Additional Commands:{{range $cmds}}{{if (and (eq .GroupID "") (or .IsAvailableCommand (eq .Name "help")))}}
  {{rpad .Name .NamePadding }} {{.Short}}{{end}}{{end}}{{end}}{{end}}{{end}}{{if .HasAvailableLocalFlags}}

Flags:
{{.LocalFlags.FlagUsages | trimTrailingWhitespaces}}{{end}}{{if .HasAvailableInheritedFlags}}

Global Flags:
{{.InheritedFlags.FlagUsages | trimTrailingWhitespaces}}{{end}}{{if .HasHelpSubCommands}}

Additional help topics:{{range .Commands}}{{if .IsAdditionalHelpTopicCommand}}
  {{rpad .CommandPath .CommandPathPadding}} {{.Short}}{{end}}{{end}}{{end}}{{if .HasAvailableSubCommands}}

Use "{{.CommandPath}} [command] --help" for more information about a command.{{end}}
`

// Execute runs the root command.
func Execute() error {
	return rootCmd.Execute()
}

// SetVersion sets the version string on the root command.
func SetVersion(v string) {
	rootCmd.Version = v
	version = v
}

func init() {
	cobra.OnInitialize(initConfig)

	helpDefault := "~/.config/snappy/config.yaml"
	if p, err := config.DefaultConfigPath(); err == nil {
		if home, err := os.UserHomeDir(); err == nil {
			sep := string(os.PathSeparator)
			if strings.HasPrefix(p, home+sep) {
				rel := strings.TrimPrefix(p, home)
				helpDefault = "~" + rel
			} else {
				helpDefault = p
			}
		} else {
			helpDefault = p
		}
	}

	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "",
		fmt.Sprintf("config file (default: %s)", helpDefault))
	rootCmd.CompletionOptions.HiddenDefaultCmd = true

	// Register useArgs for the usage template: extracts positional-arg
	// placeholders from a command's Use field (e.g. "[command]" from
	// "help [command]") without the [flags] suffix that .UseLine appends.
	cobra.AddTemplateFunc("useArgs", func(cmd *cobra.Command) string {
		args := strings.TrimPrefix(cmd.Use, cmd.Name())
		return strings.TrimSpace(args)
	})

	// Override the default usage template so that runnable commands with
	// subcommands show a single combined usage line instead of two separate
	// lines ("snappy [flags]" and "snappy [command]").
	rootCmd.SetUsageTemplate(usageTemplate)
}

func initConfig() {
	if cfgFile != "" {
		viper.SetConfigFile(cfgFile)
	} else {
		defaultPath, err := config.DefaultConfigPath()
		if err == nil {
			viper.AddConfigPath(filepath.Dir(defaultPath))
			viper.SetConfigName("config")
			viper.SetConfigType("yaml")
		}
	}

	viper.SetEnvPrefix("SNAPPY")
	viper.AutomaticEnv()
	config.SetDefaults()

	if err := viper.ReadInConfig(); err != nil {
		if _, ok := err.(viper.ConfigFileNotFoundError); !ok {
			fmt.Fprintf(os.Stderr, "Warning: config file error: %v\n", err)
		}
	}
}

func runTUI(_ *cobra.Command, _ []string) error {
	if _, err := exec.LookPath("tmutil"); err != nil {
		return fmt.Errorf("tmutil not found: this tool requires macOS with Time Machine support")
	}

	cfg := config.Load()

	log := logger.New(logger.Options{
		LogDir:     cfg.LogDir,
		MaxEntries: 50,
		MaxSize:    cfg.LogMaxSize,
		MaxFiles:   cfg.LogMaxFiles,
	})
	defer log.Close()
	log.LoadTail()

	runner := platform.OSRunner{}
	startupCtx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	// One-time startup: discover APFS volume and check TM status
	apfsVolume, err := platform.FindAPFSVolume(startupCtx, runner, config.DefaultMount)
	if err != nil {
		log.Log(logger.LevelWarn, logger.CatStartup, fmt.Sprintf("Failed to discover APFS volume for %s: %v", config.DefaultMount, err))
	}
	tmStatus := platform.CheckStatus(startupCtx, runner)

	volumeName := config.DefaultMount
	var apfsContainer string
	if mountInfo, mountErr := platform.GetMountInfo(startupCtx, runner, config.DefaultMount); mountErr == nil {
		if mountInfo.VolumeName != "" {
			volumeName = mountInfo.VolumeName
		}
		apfsContainer = mountInfo.APFSContainerReference
	}

	log.Log(logger.LevelInfo, logger.CatStartup, startupSummary(version, volumeName, cfg.RefreshInterval))
	if apfsVolume != "" {
		log.Log(logger.LevelInfo, logger.CatStartup, fmt.Sprintf("apfs-volume=%s", apfsVolume))
	}
	if apfsContainer != "" {
		log.Log(logger.LevelInfo, logger.CatStartup, fmt.Sprintf("apfs-container=%s", apfsContainer))
	}
	// Check if a background daemon holds the auto-snapshot lock.
	lockPath := service.DefaultLockPath(cfg.LogDir)
	daemonActive := service.IsHeld(lockPath)

	if daemonActive {
		log.Log(logger.Startup, "Background service detected; TUI auto-snapshots disabled")
	}
	log.Log(logger.LevelInfo, logger.CatStartup, fmt.Sprintf("auto-snapshot=%v | every %ds | thin >%ds to %ds",
		cfg.AutoEnabled, int(cfg.AutoSnapshotInterval.Seconds()),
		int(cfg.ThinAgeThreshold.Seconds()), int(cfg.ThinCadence.Seconds())))

	model := tui.NewModel(cfg, runner, log, apfsVolume, apfsContainer, tmStatus, volumeName, version, daemonActive)
	p := tea.NewProgram(model)

	if _, err := p.Run(); err != nil {
		return fmt.Errorf("running TUI: %w", err)
	}

	return nil
}

func startupSummary(version, volumeName string, refreshInterval time.Duration) string {
	return fmt.Sprintf("snappy %s | volume=%s | refresh=%ds",
		version, volumeName, int(refreshInterval.Seconds()))
}
