name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  release:
    uses: cboone/gh-actions/.github/workflows/go-release.yml@main
    with:
      runs-on: macos-latest
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
